[build]
    # Root of package.json, etc
    base = "./"
    # The command to run production build
    command = "npm run build"
    # Publish directory
    publish = "dist/"

[[redirects]]
    from = "/*"
    to = "http://austinhale.cph426.com/"
